version: '3.8'

services:
  cookbook:
    image: cookbook:latest
    build: .
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 1337:1337
    volumes:
      - ./recipes:/app/recipes
